### ISSUE TITLE
1주차 문제

### ISSUE THREAD

**Issue by dldbdud314** [codingtest-repository/codingtest#4]
## 📝 발행 문제

- [백준 1439](https://www.acmicpc.net/problem/1439)
- [무지의 먹방 라이브](https://school.programmers.co.kr/learn/courses/30/lessons/42891)
- [백준 11403](https://www.acmicpc.net/problem/11403)
- [백준 2661](https://www.acmicpc.net/problem/2661)
- [백준 9935](https://www.acmicpc.net/problem/9935)

## 👉 특이사항

- 링크를 타고 이동할 수 있도록 하이퍼링크로 남겨주세요.
- 본인 영문 이름 소문자 브랜치 생성 후 그 곳에 코드 푸시 후 라이브 코테 이후 Merge 할게요.
- 불가피하게 지킬 수 없는 경우에는 당일 말고 사전에 미리 알려주세요.

**Comment by dnwls16071** [comment]
확인했습니다
